### ISSUE TITLE
Getting started is confusing for beginners

### ISSUE THREAD

**Issue by bbstilson** [rekibnikufesin/elasticsearch-intro#5]
Hey there,

I just started your course on egghead.io, and I had a bit of trouble getting started. I think expanding the README to include steps on getting docker up and running would be useful. Something like:

---

# Running Locally

If you do not have Docker installed yet, you'll want to download it: [OSX](https://www.docker.com/docker-mac) | [Windows](https://www.docker.com/docker-windows)

After Docker has finished installing, do the following:

```bash
git clone https://github.com/rekibnikufesin/elasticsearch-intro.git
cd elasticsearch-intro
docker-compose up
```

This will set up a basic elasticsearch and kibana server for us to experiment on.

Next, you'll need to load the [sample data](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data) into the Elasticsearch cluster. To do so:

```bash
npm install
npm run import
```

That's it! Enjoy the course!

---

I'd be happy to submit a PR for these changes as well if that would be easier. I've submitted a PR for the import script [here](https://github.com/rekibnikufesin/elasticsearch-intro/pull/4)

**Comment by rekibnikufesin** [comment]
Sorry I missed this until now. Your PR looks great and has been merged.
Thanks!
