### ISSUE TITLE
Unable to connect to elastic search

### ISSUE THREAD

**Issue by dandersh** [rekibnikufesin/elasticsearch-intro#7]
I am new to docker, elastic search, etc. and am using the default configuration and am unable to connect to elastic search after trying the steps outlined in the other issues. It appears to a connection error where I have to point to a different url but I'm not sure where I would do that (I tried pointing to http://elasticsearch:9200 to no avail) or if I am even correct. 

When running node utils/import.js it completes processing and then returns this error:

Elasticsearch ERROR: 2017-04-29T17:33:28Z
  Error: Request error, retrying
  POST http://localhost:9200/_bulk => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/lodash/lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)

Elasticsearch WARNING: 2017-04-29T17:33:28Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-04-29T17:33:28Z
  No living connections

{ Error: No Living connections
    at sendReqWithConnection (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/elasticsearch/src/lib/transport.js:207:15)
    at next (/Users/dandersh/Code/Elastic_Search/elasticsearch-intro/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) message: 'No Living connections' }

Running docker-compose up returns this error log:

Starting elasticsearchintro_elasticsearch_1
Starting elasticsearchintro_kibana_1
Attaching to elasticsearchintro_elasticsearch_1, elasticsearchintro_kibana_1
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","plugin:kibana@5.3.1","info"],"pid":8,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","plugin:elasticsearch@5.3.1","info"],"pid":8,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["error","elasticsearch","admin"],"pid":8,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.18.0.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","plugin:console@5.3.1","info"],"pid":8,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
elasticsearch_1  | [2017-04-29T17:23:52,624][INFO ][o.e.n.Node               ] [] initializing ...
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","plugin:elasticsearch@5.3.1","error"],"pid":8,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","plugin:timelion@5.3.1","info"],"pid":8,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["listening","info"],"pid":8,"message":"Server running at http://0.0.0.0:5601"}
elasticsearch_1  | [2017-04-29T17:23:52,731][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_121]
elasticsearch_1  | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_121]
elasticsearch_1  | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_121]
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:262) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
elasticsearch_1  | 	... 6 more
elasticsearchintro_elasticsearch_1 exited with code 1
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:52Z","tags":["status","ui settings","error"],"pid":8,"state":"red","message":"Status changed from uninitialized to red - Elasticsearch plugin is red","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:54Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:54Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:57Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:23:57Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:00Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:00Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:02Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:02Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:05Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-29T17:24:05Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}

What am I doing wrong?

**Comment by rekibnikufesin** [comment]
Hey- 
sorry to hear you're having trouble, I know I did at first as well (especially if you're taking on Docker and Elasticsearch at the same time).
My first instinct is that you're Docker virtual machine isn't configured with enough RAM to run Elasticsearch. Take a look at this, I think it will help (specifically the last comment on increasing memory allocated): https://github.com/rekibnikufesin/nodejs-api-swagger/issues/2
Once it's up, you will be able to access elasticsearch at http://localhost:9200 but *not* http://elasticsearch:9200. The hostname `elasticsearch` is defined inside of the container and is used by other docker containers to talk to elasticsearch (without sending the traffic across your local network). Port 9200 is exposed externally allowing you to access it via localhost.
Let me know if that helps, if not- I'll help you get it resolved!

**Comment by mtham8** [comment]
Hello,

I've increased the memory for Docker (to 5GB), but when I try to run `node utils/import.js`, I still get the same error 

```
Processing complete
Elasticsearch ERROR: 2017-04-29T20:38:01Z
  Error: Request error, retrying
  POST http://localhost:9200/_bulk => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/lodash/lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1276:8)

Elasticsearch WARNING: 2017-04-29T20:38:01Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-04-29T20:38:01Z
  No living connections

{ Error: No Living connections
    at sendReqWithConnection (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/elasticsearch/src/lib/transport.js:207:15)
    at next (/Users/mtham/Documents/egghead/elasticsearch-intro/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) message: 'No Living connections' }
```

**Comment by mtham8** [comment]
Nevermind, fixed it. Forgot to run `docker-compose up` before running `node utils/import.js` - oops!

For anyone who's getting started:
PRE: install Docker and increase memory size to ~ 4GB [https://github.com/rekibnikufesin/nodejs-api-swagger/issues/2)]

1. `cd elasticsearch-intro`
2. `docker-compose up`
3.  `node utils/import.js`

then start Lesson 1.

**Comment by rekibnikufesin** [comment]
Right on @mtham8! Glad you got it working!

**Comment by dandersh** [comment]
I tried adding memory via the cli (http://stackoverflow.com/questions/32834082/how-to-increase-docker-machine-memory-mac) and I am still seeing the same issue. I'm thinking it may be an issue of me running Mavericks and thus using the DockerToolbox installer as I am not on the minimum supported version for Docker (which is Yosemite). I may have to bite the bullet and upgrade to Sierra.

**Comment by rekibnikufesin** [comment]
That seems likely. Any reason you're still on Mavericks? I was an early adopter of Sierra (regretted it) but it seems pretty stable now.

**Comment by dandersh** [comment]
Yea I've held off due to stability issues and didn't really have a pressing need (until now). I'm not able to back up for an upgrade at this time so I'll close this out. Thanks for your help.
